AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  reportMetric:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: reportMetric
      Description: ''
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: 'arn:aws:iam::870717836641:role/DDBFullAccess'
      Runtime: python3.7
      Timeout: 3
